from py8583 import DT, LT
    

Iso1987Ascii = {
         2:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 19,  'Description': 'Primary account number', 'LenType': LT.LLVAR, 'LenDataType': DT.ASCII },
         3:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 6,   'Description': 'Processing code', 'LenType': LT.FIXED },
         4:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 12,  'Description': 'Amount, transaction', 'LenType': LT.FIXED },
         5:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 12,  'Description': 'Amount, settlement', 'LenType': LT.FIXED },
         6:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 12,  'Description': 'Amount, cardholder billing', 'LenType': LT.FIXED },
         7:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 10,  'Description': 'Transmission date & time', 'LenType': LT.FIXED },
         8:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 8,   'Description': 'Amount, cardholder billing fee', 'LenType': LT.FIXED },
         9:  {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 8,   'Description': 'Conversion rate, settlement', 'LenType': LT.FIXED },
         10: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 8,   'Description': 'Conversion rate, cardholder billing', 'LenType': LT.FIXED },
         11: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 6,   'Description': 'System trace audit number', 'LenType': LT.FIXED },
         12: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 6,   'Description': 'Time, local transaction (hhmmss)', 'LenType': LT.FIXED },
         13: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 4,   'Description': 'Date, local transaction (MMDD)', 'LenType': LT.FIXED },
         14: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 4,   'Description': 'Date, expiration', 'LenType': LT.FIXED },
         15: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 4,   'Description': 'Date, settlement', 'LenType': LT.FIXED },
         16: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 4,   'Description': 'Date, conversion', 'LenType': LT.FIXED },
         17: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 4,   'Description': 'Date, capture', 'LenType': LT.FIXED },
         18: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 4,   'Description': 'Merchant type', 'LenType': LT.FIXED },
         19: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 3,   'Description': 'Acquiring institution country code', 'LenType': LT.FIXED },
         20: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 3,   'Description': 'PAN extended, country code', 'LenType': LT.FIXED },
         21: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 3,   'Description': 'Forwarding institution. country code', 'LenType': LT.FIXED },
         22: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 3,   'Description': 'Point of service entry mode', 'LenType': LT.FIXED },
         23: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 3,   'Description': 'Application PAN sequence number', 'LenType': LT.FIXED },
         24: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 3,   'Description': 'Network International identifier', 'LenType': LT.FIXED },
         25: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 2,   'Description': 'Point of service condition code', 'LenType': LT.FIXED },
         26: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 2,   'Description': 'Point of service capture code', 'LenType': LT.FIXED },
         27: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 1,   'Description': 'Authorizing identification response length', 'LenType': LT.FIXED },
         28: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 9,   'Description': 'Amount, transaction fee', 'LenType': LT.FIXED }, # x+n 8 where x can be a character 
         29: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 9,   'Description': 'Amount, settlement fee', 'LenType': LT.FIXED }, # x+n 8 where x can be a character
         30: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 9,   'Description': 'Amount, transaction processing fee', 'LenType': LT.FIXED }, # x+n 8 where x can be a character
         31: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 9,   'Description': 'Amount, settlement processing fee', 'LenType': LT.FIXED }, # x+n 8 where x can be a character
         32: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 11,  'Description': 'Acquiring institution identification code', 'LenType': LT.LLVAR, 'LenDataType': DT.ASCII },
         33: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 11,  'Description': 'Forwarding institution identification code', 'LenType': LT.LLVAR, 'LenDataType': DT.ASCII },
         34: {'DataType': DT.ASCII, 'ContentType':'ns',  'MaxLen': 28,  'Description': 'Primary account number, extended', 'LenType': LT.LLVAR, 'LenDataType': DT.ASCII },
         35: {'DataType': DT.ASCII, 'ContentType':'z',   'MaxLen': 37,  'Description': 'Track 2 data', 'LenType': LT.LLVAR, 'LenDataType': DT.ASCII },
         36: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 104, 'Description': 'Track 3 data', 'LenType': LT.LLLVAR,'LenDataType': DT.ASCII },
         37: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 12,  'Description': 'Retrieval reference number', 'LenType': LT.FIXED },
         38: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 6,   'Description': 'Authorization identification response', 'LenType': LT.FIXED },
         39: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 2,   'Description': 'Response code', 'LenType': LT.FIXED },
         40: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 3,   'Description': 'Service restriction code', 'LenType': LT.FIXED },
         41: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 8,   'Description': 'Card acceptor terminal identification', 'LenType': LT.FIXED },
         42: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 15,  'Description': 'Card acceptor identification code', 'LenType': LT.FIXED },
         43: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 40,  'Description': 'Card acceptor name/location', 'LenType': LT.FIXED },
         44: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 25,  'Description': 'Additional response data', 'LenType': LT.LLVAR , 'LenDataType': DT.ASCII },
         45: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 76,  'Description': 'Track 1 data', 'LenType': LT.LLVAR , 'LenDataType': DT.ASCII },
         46: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 999, 'Description': 'Additional data - ISO', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         47: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 999, 'Description': 'Additional data - national', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         48: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 999, 'Description': 'Additional data - private', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         49: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 3,   'Description': 'Currency code, transaction', 'LenType': LT.FIXED },
         50: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 3,   'Description': 'Currency code, settlement', 'LenType': LT.FIXED },
         51: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 3,   'Description': 'Currency code, cardholder billing', 'LenType': LT.FIXED },
         52: {'DataType': DT.ASCII, 'ContentType':'b',   'MaxLen': 8,   'Description': 'Personal identification number data', 'LenType': LT.FIXED }, # b length is always defined in binary bytes so it's double in ASCII
         53: {'DataType': DT.ASCII, 'ContentType':'n',   'MaxLen': 16,  'Description': 'Security related control information', 'LenType': LT.FIXED },
         54: {'DataType': DT.ASCII, 'ContentType':'an',  'MaxLen': 120, 'Description': 'Additional amounts', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         55: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved ISO', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         56: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved ISO', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         57: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved national', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         58: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved national', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         59: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved national', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         60: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved national', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         61: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved private', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         62: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved private', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         63: {'DataType': DT.ASCII, 'ContentType':'ans', 'MaxLen': 999, 'Description': 'Reserved private', 'LenType': LT.LLLVAR, 'LenDataType': DT.ASCII },
         64: {'DataType': DT.ASCII, 'ContentType':'b',   'MaxLen': 8,   'Description': 'Message authentication code (MAC)', 'LenType': LT.FIXED }, # b length is always defined in binary bytes so it's double in ASCII
    }